# Site title
title = "Andromeda"
base_url = "https://www.andromeda.is"
description = "Welcome to Andromeda."
compile_sass = true
theme = "andromeda"

[extra]
header_links = [
    # {name = "Projects", url = "/https://igneousearth.github.io/projects/pic16/pic16f88.html"},
    {name = "S.V. Andromeda", url="/ship/"},
    {name = "Australia", url = "/blog"}
]
license = "CC BY-NC 2.0"
favicon = "/images/favicon.ico"
email = "parker@plamb.com"
name = "Parker Lamb"
